#Пожалуйста, проверьте все наши обновление.
#spigot: https://www.spigotmc.org/resources/businesssign-plugin-for-businesses-1-12-2.88056/
#check update, pls.
Info:
  money: 0
  owner: 'Null'
  material: 0
GUI:
  NameGUI: '&aShop'
  NameApple: '&cApple'
  LoreApple: '&cApple&f: 150 money, 15 number, you balance:'
  NameBread: '&6Bread'
  LoreBread: '&6Bread&f: 40 money, you balance:'
  NamePotato: '&aPotato'
  LorePotato: '&aPotato: &f90 money, 5 number, you balance:'
  NameMilk: '&fMilk'
  LoreMilk: '&fMilk: 50 money, you balance:'
  NameFishing: '&3Fishing Rod'
  LoreFishing: '&3Fishing Rod&f: 500 money, you balance:'
  NameBook: '&cWritable Book'
  LoreBook: '&cWritable Book&f: 100 money, you balance:'
  NameClock: '&eClock'
  LoreClock: '&eClock&f: 150 money, you balance:'
  NameCompass: '&7Compass'
  LoreCompass: '&7Compass&f: 100 money, you balance:'
  NameSteel: '&4Flint and Steel'
  LoreSteel: '&4Flint and Steel&f: 200 money, you balance:'
Messages:
  Prefix: '&7<<&aBusiness&7>>:'
  BuyAppleMessage: '&aYou bought apples for 150 money'
  BuyBreadMessage: '&aYou bought bread for 40 money'
  BuyPotatoMessage: '&aYou bought potato for 90 money'
  BuyMilkMessage: '&aYou bought milk for 50 money'
  BuyFishingMessage: '&aYou bought Fishing rod for 500 money'
  BuyBookMessage: '&aYou bought Book for 100 money'
  BuyClockMessage: '&aYou bought Clock for 150 money'
  BuyCompassMessage: '&aYou bought Compass for 100 money'
  BuySteelMessage: '&aYou bought Flint and Sleet for 200 money'
  InsufficientFundsBreadMessage: '&cYou dont have enough funds buy bread'
  InsufficientFundsAppleMessage: '&cYou dont have enough funds buy apple'
  InsufficientFundsPotatoMessage: '&cYou dont have enough funds buy potato'
  InsufficientFundsMilkMessage: '&cYou dont have enough funds buy milk'
  InsufficientFundsFishingMessage: '&cYou dont have enough funds buy fishing rod'
  InsufficientFundsBookMessage: '&cYou dont have enough funds buy writable book'
  InsufficientFundsClockMessage: '&cYou dont have enough funds buy clock'
  InsufficientFundsCompassMessage: '&cYou dont have enough funds buy compass'
  InsufficientFundsSteelMessage: '&cYou dont have enough funds buy Flint and Steel'
  InsufficientBusinessSucessMessage: '&aYou have successfully withdrawn money from
    the business:'
  InsufficientBusinessFailedMessage: '&cThere are 0 coins on the business balance.'
  InsufficientBusinessBalanceMessage: '&fBalance of your business:'
  Error: Unfortunately you are not a business owner
  BuyOwnerShopGUI: '&cYou owner business'
  NullMaterial: '&cthe business ran out of materials.'
  InsufficientBusinessMaterialMessage: ''
  AddStaffError: '&cYou have already added this player.'
  AddStaffMessage: '&aYou have successfully added a player.'
  StaffNullMessage: '&cEnter the player.'
  RemoveStaffMessage: '&aYou have successfully remove a player.'
  AddWorkerError: '&cYou have already added this player.'
  AddWorkerMessage: '&aYou have successfully added a player.'
  WorkerNullMessage: '&cEnter the player.'
  RemoveWorkerMessage: '&aYou have successfully remove a player.'
  RemoveWorkerError: '&cYou have already added this player.'
Price:
  ApplePrice: 150
  BreadPrice: 40
  PotatoPrice: 90
  MilkPrice: 50
  FishingPrice: 500
  BookPrice: 100
  ClockPrice: 150
  CompassPrice: 100
  SteelPrice: 200
  MaterialTake: 15
NumberGive:
  NumberAppleGive: 15
  NumberBreadGive: 1
  NumberPotatoGive: 5
  NumberMilkGive: 1
  NumberFishingGive: 1
  NumberBookGive: 1
  NumberClockGive: 1
  NumberCompassGive: 1
  NumberSteelGive: 1
Sign:
  Prefix: '[BusinessSet]'
  InvalidPrice: '&cInvalid price'
  FirstLine: 'Business:'
  TwoLine: 'Price:'
  BusinessErrorBuy: The business is already bought!
  InsufficientFundsMessage: '&cYou dont have enough funds buy Business'
  MessageBusinessBuy: 'You have buy business:'
  ThirdLine: 'bought:'
  MessageTitleBusinessBuy: '&aYou have buy business!'
  MessageTitleBusinessBuyTwoLine: '&aHappy you'
  MessageRegionNull: '&cRegion is null.'
JoinAndQuit:
  MessageJoin: '&aBusinessMan %prefix% &f%player% %suffix% &fjoin server.'
  Join: true
  MessageQuit: '&aBusinessMan %prefix% &f%player% %suffix% &fleave server.'
  Quit: true
ScoreBoard:
  ScoreBoard: true
  NameScoreBoard: '&6Business'
  LoreScoreBoard: '&amoney:'
  LoreScoreBoard2: '&amaterial:'
MaterialGUI:
  NameGUI: '&aMaterial business'
  MaterialSlot3: 300
  SkullName3: '&aMaterial'
  SkullLore3: '&7Materials: 300, price: 4.500, you balance:'
  MaterialSlot7: 1500
  SkullName7: '&aMaterial'
  SkullLore7: '&7Materials: 1.500, price: 22.500, you balance:'
  SkullName5: '&aInfo.'
  SkullLore5: '&7Total material:&f'
  SkullLore5TwoLine: '&7Total balance:&f'
  SkullLore5ThreeLine: '&7Staff:&f'
  SkullLore5FourLine: '&7The money received today:&f'
  BalanceSlot2: 5000
  SkullName2: '&aBalance'
  SkullLore2: '&7Pay balance business: 5.000, you balance:'
  BalanceSlot8: 10000
  SkullName8: '&aBalance'
  SkullLore8: '&7Pay balance business: 10.000, you balance:'
  NullMaterial: '&cYou dont have enough money to buy the materials.'
  BuyMaterialMessage: '&aYou have successfully purchased the materials.'
  BuyBalanceMessage: '&aYou have replenished the balance of the business'
  SkullMaterialInfo: MHF_Exclamation
  SkullMaterialBalance: MrSnowDK
  MaterialTake: 15
  SkullMaterial: BigG0628
Taxes:
  Taxes: true
  message: '[Unified Tax Service] 300 coins were withdrawn from the business.'
  money: 300
Vote:
  MessageFalse: Vote not started.
  MessageTrue: Select a candidate by giving the administrator a piece of paper
  BroadcastMessageStartVote: '&7<<&aBusiness&7>>: Voting has begun! Candidate: %arg1%,
    %arg2%, %arg3%.'
  BroadcastMessageStopVote: '&7<<&aBusiness&7>>: Voting stopped.'
  start: 'false'
  Nick1: ''
  Nick2: ''
  Nick3: ''
Staff: '[]'
#Пожалуйста, проверьте все наши обновление.
#spigot: https://www.spigotmc.org/resources/businesssign-plugin-for-businesses-1-12-2.88056/
#check update, pls.