name: Business
main: Boss90.RegionSheller.GLClass
description: Simple plugin
version: 0.1
commands:
  shopGUI:
    description: Shows info is Player.
    usage: /news [TEXT]
  sbalance:
    description: Shows info is Player.
    usage: /news [TEXT]
  stakebalance:
    description: Shows info is Player.
    usage: /news [TEXT]
  shelp:
    description: Shows info is Player.
    usage: /news [TEXT]|
  sremoveowner:
    description: Shows info is Player.
    usage: /news [TEXT]
  swipebusiness:
    description: Shows info is Player.
    usage: /news [TEXT]
  sreload:
    description: Shows info is Player.
    usage: /news [TEXT]
  smaterial:
    description: Shows info is Player.
    usage: /news [TEXT]
  saddstaff:
    description: Shows info is Player.
    usage: /news [TEXT]
  sremovestaff:
    description: Shows info is Player.
    usage: /news [TEXT]
  saddworker:
    description: Shows info is Player.
    usage: /news [TEXT]
  sremoveworker:
    description: Shows info is Player.
    usage: /news [TEXT]
  sstartvote:
    description: Shows info is Player.
    usage: /news [TEXT]
  svote:
    description: Shows info is Player.
    usage: /news [TEXT]
  sstopvote:
    description: Shows info is Player.
    usage: /news [TEXT]
  ssetowner:
    description: Shows info is Player.
    usage: /news [TEXT]